### ISSUE TITLE
not beeing able to parse complete routes tree

### ISSUE THREAD

**Issue by eikaramba** [Bewinxed/svelte-matey#1]
not sure what is going on, but i only see the first folder with a dynamic variable in my tree. nothing else

![grafik](https://github.com/Bewinxed/svelte-matey/assets/1320525/4663be0e-ac83-491c-96b6-ed545600c1ec)

**Comment by Bewinxed** [comment]
Just pushed an update that fixed this:

![image](https://github.com/Bewinxed/svelte-matey/assets/9145989/b0326453-f3c1-49c7-b0ba-88e6fcf4b06f)

also now can browse +page.svelte too!

**Comment by eikaramba** [comment]
works now although it looks little bit confusing for me. i have many duplicates or empty folders
![grafik](https://github.com/Bewinxed/svelte-matey/assets/1320525/8b1bf87b-04d8-4d16-87c8-e663db87f49c)

not sure if i should see the layout files as well. ah and neither the parsing of my page files or endpoints works. but i suspect that is because i don't use typescript.

in any case keep up the work, i think that plugin can become really useful. just opening tickets here to give you some insights about different setups :)

**Comment by Bewinxed** [comment]
Can you try reloading then waiting for a bit before interacting with it?
I'll figure it out.

I have a filter atm for .ts files, but i'll see what i can do

Thanks for the updates!

**Comment by eikaramba** [comment]
reloading and waiting did not change anything. i use a quite complicated way of enabling i18n for my sveltekit project. i guess that might be the reason. but not a problem for now.

**Comment by Bewinxed** [comment]
I was trying to make loading faster by building an index of the files.

Looks I need a bit of fine tuning, I'll fix it quick, thanks for trying it
out!
